# Generated by Django 6.0.3 on 2026-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_standardpage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionindexpage",
            name="section_type",
        ),
    ]
